### ISSUE TITLE
Asking help 

### ISSUE THREAD

**Issue by blaise98-dev** [safak/youtube#11]
Hello safak, i tried to run " npm install " but gives the following error:

npm ERR! Response timeout while trying to fetch https://registry.npmjs.org/react (over 30000ms)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/blaise/.npm/_logs/2021-07-24T07_00_36_423Z-debug.log

can you help me as i am new to github and react js? i am studying on your youtube-mern-social-app

**Comment by safak** [comment]
Might be caused by a slow connection.

Find `time out` in the `.npmrc` file and change value to `90000`

then
npm cache clean --force

**Comment by blaise98-dev** [comment]
Thanks

**Comment by blaise98-dev** [comment]
How do you get Mongodb  url?
