### ISSUE TITLE
Cannot post using postman. Api issue

### ISSUE THREAD

**Issue by davidKipkemoi** [safak/youtube#135]
Cannot post api/auth
![image](https://user-images.githubusercontent.com/38980452/214190114-37e1c4bf-6b25-4521-af5c-25cc98b8a9de.png)

**Comment by ELIJAHKUNGU** [comment]
i would suggest send what you're receiving on the console

**Comment by davidKipkemoi** [comment]
[image: Screenshot (337).png]
There is no error in the console and everything seems okay.

**Comment by davidKipkemoi** [comment]
![Screenshot (337)](https://user-images.githubusercontent.com/38980452/214346319-b1887ac8-678d-4c14-b2a4-2270f90d48c2.png)
There is no error in the console and everything seems okay.

**Comment by ELIJAHKUNGU** [comment]
Can you open routes auth and routes page

**Comment by davidKipkemoi** [comment]
Okay. This is the auth route page.
![Screenshot (342)](https://user-images.githubusercontent.com/38980452/214446115-99daf1d6-c5b8-4360-ac39-f4dbce296acf.png)
 This is its model.
![Screenshot (343)](https://user-images.githubusercontent.com/38980452/214446442-f35d66a6-c27d-4d0f-9902-0009792f8231.png)

**Comment by davidKipkemoi** [comment]
Done.

**Comment by ELIJAHKUNGU** [comment]
kindly reach out me to at this email 

```elijahkungu100@gmail.com ```

**Comment by davidKipkemoi** [comment]
It's working.

**Comment by davidKipkemoi** [comment]
Thank you Elijah. I ended up reinstalling mongoose and express js afresh and it somehow was able to work.
