### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by sujoyduttajad** [safak/youtube#19]
Hi,
One of the slider images is not working.

[https://i.ibb.co/XsdmR2c/1.png](https://i.ibb.co/XsdmR2c/1.png)
![image](https://user-images.githubusercontent.com/33634147/135567357-fc6933c6-b17b-4971-bd59-f948d4819d56.png)

May I ask where you are getting these images? I want to put more images in the slider functionality.

**Comment by ArbiNMaki** [comment]
up.

**Comment by sujoyduttajad** [comment]
Hi, @ArbiNMaki what do you mean by "up."

**Comment by ahmadnzr** [comment]
hello @sujoyduttajad 
I think the problem come from image owner, not from lama dev. so you can change your image url with difference url.
i use this link to replace url : https://www.nicepng.com/png/full/8-88585_women-fashion-png-example-of-magazine-cover.png . but you can choose other. you can replace url by change value of img in sliderItems Object `(project/src/data.js)`

**Comment by safak** [comment]
Hi, unfortunately, I cannot share copyrighted content.

**Comment by sujoyduttajad** [comment]
No problem I understand.
