### ISSUE TITLE
GET and Uncaught (in promise) Error:

### ISSUE THREAD

**Issue by Esorethewarrior0623** [safak/youtube#2]
I have ran into two errors around the timestamp of 23:00. 

**Error 1** 
xhr.js:177 GET http://localhost:3000/posts/timeline/608f0498b0e4571414a04042 500 (Internal Server Error)
I did research and found that this is an error on the server side of the application that relates. I looked at my posts request and this is what I have (copied it from your github to make sure)

`router.get("/timeline/:userId", async (req, res) => {
  try {
    const currentUser = await User.findById(req.params.userId);
    const userPosts = await Post.find({ userId: currentUser._id });
    const friendPosts = await Promise.all(
      currentUser.followings.map((friendId) => {
        return Post.find({ userId: friendId });
      })
    );
    res.status(200).json(userPosts.concat(...friendPosts))
  } catch (err) {
    res.status(500).json(err);
    console.log(err)
  }
});`

**Error 2**
Uncaught (in promise) Error: Request failed with status code 500. I have a feeling once I get this situated, that should work as well. Any help would be greatly appreciated.

**Comment by Esorethewarrior0623** [comment]
Figured it out.

**Comment by talhaiqbal98** [comment]
How did you solve the error mate? I'm getting same error in Postman (timeline/all) part.

**Comment by oriesh** [comment]
Hey, I  am having the same issue.

Do you mind saying how you sorted it out?

Thx!

**Comment by urbutisj** [comment]
How did you fixed that ?
