### ISSUE TITLE
Cannot read properties of null (reading 'accessToken')

### ISSUE THREAD

**Issue by ayadgu** [safak/youtube#31]
I've just cloned the repo, installed dependencies of both api/client with yarn and then yarn started them.

As soon as localholst:3000 opens, I face this error :
![image](https://user-images.githubusercontent.com/6131702/138234051-58e02699-a91a-42e8-9377-8d14d620e435.png)

**Comment by JohnnyHaick** [comment]
Having the same issue. Any help?

**Comment by opholroyd** [comment]
Try researching setItem method for localStorage and try setting it?

**Comment by tarunkumargit** [comment]
@Sseast any solution for this?

**Comment by shinboizz** [comment]
> I've just cloned the repo, installed dependencies of both api/client with yarn and then yarn started them.
> 
> As soon as localholst:3000 opens, I face this error : ![image](https://user-images.githubusercontent.com/6131702/138234051-58e02699-a91a-42e8-9377-8d14d620e435.png)


I have the same error as you. Did you fix it yet? help me

**Comment by daman9999** [comment]
this might not be the best solution but try wrapping it in try catch block 
eg:
let TOKEN =""
try{
   TOKEN = JSON.parse(JSON.parse(localStorage.getItem("persist:root")).user).currentUser.accessToken || " ";
}
catch(err){
    console.log(err);
}
  
for me it works.... :)

**Comment by shinboizz** [comment]
> this might not be the best solution but try wrapping it in try catch block eg: let TOKEN ="" try{ TOKEN = JSON.parse(JSON.parse(localStorage.getItem("persist:root")).user).currentUser.accessToken || " "; } catch(err){ console.log(err); }
> 
> for me it works.... :)

support me , please. My email: phuquangle5@gmail.com

**Comment by daman9999** [comment]
> > this might not be the best solution but try wrapping it in try catch block eg: let TOKEN ="" try{ TOKEN = JSON.parse(JSON.parse(localStorage.getItem("persist:root")).user).currentUser.accessToken || " "; } catch(err){ console.log(err); }
> > for me it works.... :)
> 
> support me , please. My email: [phuquangle5@gmail.com](mailto:phuquangle5@gmail.com)

do you want me to send you the code

**Comment by shinboizz** [comment]
> > > this might not be the best solution but try wrapping it in try catch block eg: let TOKEN ="" try{ TOKEN = JSON.parse(JSON.parse(localStorage.getItem("persist:root")).user).currentUser.accessToken || " "; } catch(err){ console.log(err); }
> > > for me it works.... :)
> > 
> > 
> > support me , please. My email: [phuquangle5@gmail.com](mailto:phuquangle5@gmail.com)
> 
> do you want me to send you the code
Yes, Can you help me edit the code?

**Comment by daman9999** [comment]
> me ed

yes ofcourse

**Comment by shinboizz** [comment]
Email me, it's easier for us to fix. My email: phuquangle5@gmail.com

**Comment by senapahlevi** [comment]
> > me ed
> 
> yes ofcourse

hey pleasse email me share your fixed code i getting stuck to: senapahlevi1@gmail.com

**Comment by safak** [comment]
[fixed](https://github.com/safak/youtube/blob/mern-ecommerce-app/client/src/requestMethods.js)
