### ISSUE TITLE
Problem with the timeline API endpoint

### ISSUE THREAD

**Issue by orshemtov** [safak/youtube#5]
Hi,

I've been following 2 of your videos about the API + the client.

Now I'm following the 3rd where you combine the two into fully functional social media app.

I am having trouble with this endpoint of the API:

```
::ffff:127.0.0.1 - - [22/Jun/2021:23:02:27 +0000] "GET /api/posts/timeline/60d2614e9375bbce8a755302 HTTP/1.1" 500 2
```

For some reason it doesn't work, I've checked other endpoints they seem to work fine, I have this in my 'posts.js':

```
// Get timeline
router.get("/timeline/:userId", async (req, res) => {
  try {
    const currentUser = await User.findById(req.params.userId);
    const userPosts = await Post.find({ userId: currentUser._id });
    const friendPosts = await Promise.all(
      currentUser.followings.map((friendId) => {
        return Post.find({ userId: friendId });
      })
    );
    res.status(200).json(userPosts.concat(...friendPosts));
  } catch (err) {
    res.status(500).json(err);
  }
});
```

I've tried this from the react app, from the browser and from Postman, this endpoint just returns a 500 error.

In the browser I am seeing this message:

```
Uncaught (in promise) Error: Request failed with status code 404
```

Because of this I cannot apply the useEffect on Feed

```
useEffect(() => {
    const fetchPosts = async () => {
      const res = await axios.get("posts/timeline/60d2614e9375bbce8a755302");
      setPosts(res.data);
    };
    fetchPosts();
  }, []);
```

It automatically crashes my react app.

Any idea how to fix this?

**Comment by orshemtov** [comment]
Solved

**Comment by rennermccreath** [comment]
Hi there - how did you solve this? Thanks!

**Comment by oriesh** [comment]
Hi, some time has passed and I didn't really write down to myself what was the exact solution, but I think it has something to do in "index.js" under the api, something with specifying which type of file is the one that is uploaded, here's my eventual code:

`const express = require("express");
const app = express();
const mongoose = require("mongoose");
const dotenv = require("dotenv");
const helmet = require("helmet");
const morgan = require("morgan");
const multer = require("multer");
const userRoute = require("./routes/users");
const authRoute = require("./routes/auth");
const postRoute = require("./routes/posts");
const router = express.Router();
const path = require("path");

dotenv.config();

mongoose.connect(
  process.env.MONGO_URL,
  { useNewUrlParser: true, useUnifiedTopology: true },
  () => {
    console.log("Connected to MongoDB");
  }
);
app.use("/images", express.static(path.join(__dirname, "public/images")));

//middleware
app.use(express.json());
app.use(helmet());
app.use(morgan("common"));

const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, "public/images");
  },
  filename: (req, file, cb) => {
    cb(null, req.body.name);
  },
});

const upload = multer({ storage: storage });
app.post("/api/upload", upload.any("file"), (req, res) => {
  try {
    return res.status(200).json("File uploded successfully");
  } catch (error) {
    console.error(error);
  }
});

app.use("/api/auth", authRoute);
app.use("/api/users", userRoute);
app.use("/api/posts", postRoute);

app.listen(8800, () => {
  console.log("Backend server is running!");
});
`

**Comment by orshemtov** [comment]
> Hi there - how did you solve this? Thanks!

Hi, some time has passed and I didn't really write down to myself what was the exact solution, but I think it has something to do in "index.js" under the api, something with specifying which type of file is the one that is uploaded, here's my eventual code:

```const express = require("express");
const app = express();
const mongoose = require("mongoose");
const dotenv = require("dotenv");
const helmet = require("helmet");
const morgan = require("morgan");
const multer = require("multer");
const userRoute = require("./routes/users");
const authRoute = require("./routes/auth");
const postRoute = require("./routes/posts");
const router = express.Router();
const path = require("path");

dotenv.config();

mongoose.connect(
  process.env.MONGO_URL,
  { useNewUrlParser: true, useUnifiedTopology: true },
  () => {
    console.log("Connected to MongoDB");
  }
);
app.use("/images", express.static(path.join(__dirname, "public/images")));

//middleware
app.use(express.json());
app.use(helmet());
app.use(morgan("common"));

const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, "public/images");
  },
  filename: (req, file, cb) => {
    cb(null, req.body.name);
  },
});

const upload = multer({ storage: storage });
app.post("/api/upload", upload.any("file"), (req, res) => {
  try {
    return res.status(200).json("File uploded successfully");
  } catch (error) {
    console.error(error);
  }
});

app.use("/api/auth", authRoute);
app.use("/api/users", userRoute);
app.use("/api/posts", postRoute);

app.listen(8800, () => {
  console.log("Backend server is running!");
});
```
