### ISSUE TITLE
You can update only your account!

### ISSUE THREAD

**Issue by bcodus** [safak/youtube#61]
Following the [tutorial](https://youtu.be/ldGl6L4Vktk) on my localhost mongodb (MongoDB 4.2.17 Community) and     `"mongoose": "^6.1.8"`,  I cannot update newly registered user by PUT request:

`http://127.0.0.1:8080/api/users/61f75a28fe1972fb27963879
`
JSON body:
```
{
    "description": "New desc",
    "userID": "61f75a28fe1972fb27963879"
    
}
```
I can fetch the very same user however, using GET `http://127.0.0.1:8080/api/users/61f75a28fe1972fb27963879`. 

To avoid any typos, I just copied the code snippet from github:

```
router.put("/:id", async (req, res) => {
    if (req.body.userId === req.params.id || req.body.isAdmin) {
      if (req.body.password) {
        try {
          const salt = await bcrypt.genSalt(10);
          req.body.password = await bcrypt.hash(req.body.password, salt);
        } catch (err) {
          return res.status(500).json(err);
        }
      }
      try {
        const user = await User.findByIdAndUpdate(req.params.id, {
          $set: req.body,
        });
        res.status(200).json("Account has been updated");
      } catch (err) {
        return res.status(500).json(err);
      }
    } else {
      return res.status(403).json("You can update only your account!");
    }
  });
```

But still get:
`"You can update only your account!"
`

Appreciate your hints.

**Comment by bcodus** [comment]
OK, I figured it out. It was my stupid error. I used ` "userID"` instead of ` "userId"` in the request. Old habits die hard!

**Comment by ToxicStarboy** [comment]
> OK, I figured it out. It was my stupid error. I used ` "userID"` instead of ` "userId"` in the request. Old habits die hard!

Hey there, I am having same issue as you mentioned above but i have checked the userId which is correct on both sides. Still i am not able to sort the error. Help me!!

`const router = require("express").Router();
const bcrypt = require("bcrypt");
const User = require("../models/User");

//Update User
router.put("/:id", async (req, res) => {
  if (req.body.userId === req.params.id) {
    if (req.body.password) {
      const salt = await bcrypt.genSalt(10);
      req.body.password = await bcrypt.hash(req.body.password, salt);
    }
    try {
      const updatedUser = await User.findByIdAndUpdate(
        req.params.id,
        {
          $set: req.body,
        },
        { new: true }
      );
      res.status(200).json(updatedUser);
    } catch (err) {
      res.status(500).json(err);
    }
  } else {
    res.status(401).json("You can update only your account!");
  }
});
  
  module.exports = router;
//Delete User
//Get a User
//Follow a User
//Unfollow a User

module.exports = router`

JSON Body
{
    "desc": "New desc",
    "userId": "630f9319de0c44e7942ac824"
}
