### ISSUE TITLE
404 not found on register post method 

### ISSUE THREAD

**Issue by juankarlo26** [safak/youtube#70]
![image](https://user-images.githubusercontent.com/73022823/154864758-0f0c0431-2656-4bab-8703-a53440e0d8d3.png)
![image](https://user-images.githubusercontent.com/73022823/154864776-c52413bb-cb4b-4519-b09d-bf9645cda619.png)

i tried to change the url completely with the "localhost" not 5000 but on port 3000, apparently i tried both none of it work

**Comment by juankarlo26** [comment]
nevermind i just add the publicrequest instead of axios in the post method >_<

**Comment by nikitanaruka** [comment]
i am having same problem in login.jsx ,i am not able to login and it is giving me error (axioserror),what should i do???
