### ISSUE TITLE
Err when fetching products in console

### ISSUE THREAD

**Issue by lanaarnous01** [safak/youtube#87]
![image](https://user-images.githubusercontent.com/93349082/164812029-1debcc48-7c9b-4f29-8b17-9b715710f08f.png)

` useEffect(() => {
       
        const getProducts = async ()=> {
            try{
                
                const res = await axios.get("http://localhost:5000/api/products");
                console.log(res);
            } catch(err){

            }
        }
        getProducts();
    }, [category])`
after coding use effect and fetching products, the error appears on my console as the api and client are running at the same time 

Anyone knows whats the issue?

**Comment by AliCreator** [comment]
Two points: first try to console log the error on catch(err). It will give more details.
Second, did you add "proxy" on package.json? 
Why did you add category as a dependency on your useEffect(). I don't see any place you use it.
